### ISSUE TITLE
Use IAM Role on EC2 instead of Credentials

### ISSUE THREAD

**Issue by chetankapoor** [SecurityFTW/cs-suite#11]
We can add a new feature to use IAM role on EC2 instead of credentials. #

**Comment by shivankar-madaan** [comment]
I guess it should be working by using an IAM role on ec2 instance.Never tested it completely.
Does it fail in your case?

**Comment by chetanhomify** [comment]
I tested it. It didn't worked. 
Now I tried again it is working.

**Comment by chetankapoor** [comment]
I tested it and it didn't work. 
Now I tried again with full permission to IAM and it is working.

**Comment by chetankapoor** [comment]
This is working. I am closing this issue.
