### ISSUE TITLE
Keep Lynis version up-to-date

### ISSUE THREAD

**Issue by mboelen** [SecurityFTW/cs-suite#16]
Hi team,

As you bundle Lynis (in tools/lynis), please do a resync on a regular basis. Lynis still receives updates and the overall audit will benefit if the tool is kept up-to-date.

**Comment by shivankar-madaan** [comment]
Hi @mboelen 

Thanks for the update,we will be updating the repo by today or max tomorrow for version 3.0 having  Azure Audit as well.I will have the Lynis bundle updated as well along with that.
Will keep in mind to regularly update the bundled tools.

Thanks again

**Comment by mboelen** [comment]
Thanks, that is appreciated. You may create a small sync script for it and add to the project?

**Comment by shivankar-madaan** [comment]
Hi @mboelen 

the lynis code has been updated,for regularly updating Lynis and other bundled tools, we will be tracking it ,on this issue https://github.com/SecurityFTW/cs-suite/issues/1
Hence will be closing this

Thanks
