### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by challs1** [SecurityFTW/cs-suite#19]
I set up a new ec2 instance, apt installed git, python2.7, python-pip, gcc, and executed and performed the following commands for installation 
git clone https://github.com/SecurityFTW/cs-suite.git
cd cs-suite/
sudo python setup.py

This is my output (censored):
Traceback (most recent call last):
  File "cs.py", line 55, in <module>
    main()
  File "cs.py", line 34, in main
    from modules import localaudit
  File "/home/ec2-user/saiawsazure/cs-suite/modules/localaudit.py", line 4, in <module>
    from IPy import IP
ImportError: No module named IPy
  I have installed ipy 5.0 for python 2.7 still i am facing the same issue

**Comment by shivankar-madaan** [comment]
Could please share the command as well, which you used to run cs-suite.

**Comment by shivankar-madaan** [comment]
ok thanks
Just your IPy version as well
```
[~/git/github/cs-suite] master $ pip install IPy==5.0
Collecting IPy==5.0
  Could not find a version that satisfies the requirement IPy==5.0 (from versions: 0.73, 0.74, 0.75, 0.76, 0.80, 0.81, 0.82a0, 0.82, 0.83)
```

**Comment by challs1** [comment]
@shivankar-madaan should i upgrade the python? pip version is 18?

**Comment by shivankar-madaan** [comment]
no aws just requires python 2.7

**Comment by shivankar-madaan** [comment]
yes my pip version 18
```
~/git/github/cs-suite] master $ pip --version
pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

**Comment by challs1** [comment]
@shivankar-madaan how to solve that issue?

**Comment by shivankar-madaan** [comment]
just if you can share your IPy version?

**Comment by challs1** [comment]
@shivankar-madaan pip install ipython
Requirement already satisfied: ipython in /home/ec2-user/.local/lib/python2.7/site-packages (5.0.0)
Requirement already satisfied: traitlets>=4.2 in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (4.3.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.3 in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (1.0.15)
Requirement already satisfied: simplegeneric>0.8 in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (0.8.1)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (1.0.0)
Requirement already satisfied: pickleshare in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (0.7.4)
Requirement already satisfied: pygments in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (2.2.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (4.6.0)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (2.3.2)
Requirement already satisfied: decorator in /home/ec2-user/.local/lib/python2.7/site-packages (from ipython) (4.3.0)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python2.7/site-packages (from ipython) (38.4.0)
Requirement already satisfied: ipython-genutils in /home/ec2-user/.local/lib/python2.7/site-packages (from traitlets>=4.2->ipython) (0.2.0)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/lib/python2.7/site-packages (from traitlets>=4.2->ipython) (1.0.4)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from traitlets>=4.2->ipython) (1.9.0)
Requirement already satisfied: wcwidth in /home/ec2-user/.local/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in /home/ec2-user/.local/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython) (0.6.0)
Requirement already satisfied: scandir; python_version < "3.5" in /home/ec2-user/.local/lib/python2.7/site-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython) (1.9.0)

**Comment by challs1** [comment]
@shivankar-madaan  it was 5.0.0

**Comment by shivankar-madaan** [comment]
@challs1 I dont think we require ipython
We require IPy https://pypi.org/project/IPy/
Could you just try `pip install IPy` and see if it works

**Comment by challs1** [comment]
@shivankar-madaan i have uninstalled it and installing it again when iam installing i am getting the following errors .I am using linux server
pyasn1-modules 0.2.2 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.3.2 which is incompatible.
awscli 1.14.8 has requirement botocore==1.8.12, but you'll have botocore 1.6.2 which is incompatible.
awscli 1.14.8 has requirement s3transfer<0.2.0,>=0.1.12, but you'll have s3transfer 0.1.10 which is incompatible

**Comment by shivankar-madaan** [comment]
these errors, when you run setup.py?

**Comment by challs1** [comment]
@shivankar-madaan :  when i am trying to perform the following command i am facing the error: 
sudo python setup.py
