### ISSUE TITLE
2.x checking issue

### ISSUE THREAD

**Issue by serxansherif** [SecurityFTW/cs-suite#42]
Are there any problem azure checking 2.x rules?

![image](https://user-images.githubusercontent.com/53265420/62467588-c63a4700-b79c-11e9-9125-7e92aada8daa.png)

![image](https://user-images.githubusercontent.com/53265420/62467622-d81bea00-b79c-11e9-8fbd-3034d7838787.png)

**Comment by shivankar-madaan** [comment]
@serxansherif as per the screenshots I think `jq` is missing in the system. Can you please install or verify that jq is present

**Comment by serxansherif** [comment]
yes problem source was jq. after updating jq problem solved.
thanks!
