### ISSUE TITLE
Issue in CLI

### ISSUE THREAD

**Issue by Cybernewbies** [SecurityFTW/cs-suite#5]
I persisted with these kind of error in AWS CLI
![image](https://user-images.githubusercontent.com/36504310/36406894-2bd81832-1620-11e8-891b-25d7690b2732.png)

**Comment by shivankar-madaan** [comment]
Currently cs-suite can be run on Linux env only

**Comment by Cybernewbies** [comment]
As of now , we see that prowler will be working in linux CLI not the emulator like cygwin used for windows . Hence this has been resolved.
