### ISSUE TITLE
Issue in exporting of reports in HTML format

### ISSUE THREAD

**Issue by Cybernewbies** [SecurityFTW/cs-suite#6]
Please see the screenshot and let me know , if we have issue in the command.
![Html Reporting error](https://user-images.githubusercontent.com/36504310/36596677-7a025398-18cc-11e8-9847-e5317530b8a7.png)

**Comment by Cybernewbies** [comment]
As of now , this is resolved

**Comment by shumyster** [comment]
I got the same error today 15/03/19. 
i ran the setup.py and for the "Default output format", instead of "html" I typed "json".
Then the scan (sudo python cs.py -env aws) ran with no issue, and the output was eventually in html:

>> THE FINAL REPORT IS LOCATED AT -------->  /home/ubuntu/cs-suite/reports/AWS/aws_audit/***********/20190315-135719/final_report/report.html
