### ISSUE TITLE
how to open html file after the report is generated

### ISSUE THREAD

**Issue by Leectan** [SecurityFTW/cs-suite#8]
After the report is generated, does it automatically export it to the default browser or it has to be manually open? If so, how? Any suggestion or help is appreciated here.

**Comment by shivankar-madaan** [comment]
Hi
Yes the report automatically opens to the default browser,if it hasn't you can open it from this path
`cs-suite/reports/aws_audit/<account_name>/<timestamp>/finalreport.html`
Could you let us know your default browser,as we have tested with Google chrome.We can try resolving if the case is different.
Also just for the heads up,if development branch has been cloned,then it wouldnt work as work is still in progress on that branch.

**Comment by Leectan** [comment]
I have tried the path but unfortunately it says "Your file was not found". The report does not automatically show up in browser and I've made sure I pulled it from the stable master branch. Any Advise?

**Comment by shivankar-madaan** [comment]
Could you share what was the command,you used to run the cs-suite

**Comment by Leectan** [comment]
Sure, I ran the python cs.py in the terminal as usual. 
<img width="748" alt="1" src="https://user-images.githubusercontent.com/24819052/37220112-970f62ec-2393-11e8-8a70-3785da4b79ad.png">
<img width="795" alt="2" src="https://user-images.githubusercontent.com/24819052/37220119-9ab1a52c-2393-11e8-88d9-f7af3e92eb43.png">
<img width="847" alt="4" src="https://user-images.githubusercontent.com/24819052/37220124-9f208aba-2393-11e8-8745-91bc4e666cbf.png">
<img width="996" alt="3" src="https://user-images.githubusercontent.com/24819052/37220137-a5c1bf10-2393-11e8-89bb-a81b2238a43a.png">
<img width="927" alt="screen shot 2018-03-09 at 11 57 08 am" src="https://user-images.githubusercontent.com/24819052/37220140-a9165716-2393-11e8-8949-a06b7a990ae9.png">

**Comment by Leectan** [comment]
Like I said, it did not automatically pop up the browser neither does the manual process works.

**Comment by shivankar-madaan** [comment]
Is it possible that you can navigate to that directory and check what files are available under that directory. `cs-suite/reports/aws_audit/<account_name>/<timestamp>/final_report`.
This can help us debug more into this,currently I think this is the way we can go ahead and find the issue.
Could also let me know what files are present under that directory.

**Comment by Leectan** [comment]
<img width="776" alt="1" src="https://user-images.githubusercontent.com/24819052/37223521-d04280f2-239e-11e8-9d8c-c866d4e5438c.png">
<img width="786" alt="2" src="https://user-images.githubusercontent.com/24819052/37223528-d44f1926-239e-11e8-9d8e-37e7a4cef43b.png">
<img width="952" alt="3" src="https://user-images.githubusercontent.com/24819052/37223531-d7a1189a-239e-11e8-8b63-e56bc9c9a97d.png">

**Comment by shivankar-madaan** [comment]
Are you running on your local machine or is this a ssh session?

**Comment by Leectan** [comment]
ssh session. ec2 ubuntu server.

**Comment by shivankar-madaan** [comment]
Oh then you would have copy the file/report back to your own localhost/machine via scp to view it in the browser

**Comment by Leectan** [comment]
yes, I spent the whole night try to figure that out. I scp the whole final report folder, but when open the file, it says the objection above, "Your File Was Not Found"

**Comment by shivankar-madaan** [comment]
Or another way to go around this is,you could configure the aws keys on localhost/machine itself with `aws configure`,and then run cs.py,the report would generate on your localhost itself and by default it would open in your own browser

**Comment by Leectan** [comment]
ok Thanks shivankar. Let me give that a try.

**Comment by Leectan** [comment]
Ok, after the local test, I was able to run and generate the file, but for some reason, Scout2 report is not showing. I ran it 2 times and the issue still persist.
<img width="1007" alt="2" src="https://user-images.githubusercontent.com/24819052/37232711-2e37cd60-23be-11e8-8031-38d025d0dda0.png">
<img width="922" alt="1" src="https://user-images.githubusercontent.com/24819052/37232718-32b4f3b8-23be-11e8-9ae2-46e4da6ed7de.png">

**Comment by Leectan** [comment]
and IP audit as well.
<img width="735" alt="3" src="https://user-images.githubusercontent.com/24819052/37232786-789f3f82-23be-11e8-8e7c-0cba57963f18.png">

**Comment by shivankar-madaan** [comment]
Hey 
Are u still getting this error?
sorry about the late response,was afk.
Please let us know,we'll get this debugged

**Comment by jayeshchauhan** [comment]
Hi Leectan,

If you haven't run a successful audit(Using CS-Suite) in past, the folder "local_audit" doesn't get created. So, it will always give this error of not found.
For AWS report, can you _cd_ into the directory which has cs-suite and give us the directory listing result screenshot.
Also, do the same for the report folder, _cd_ into _reports_ folder and give us a directory listing image.
If you keep finding expected folders, reach to _cs-suite/reports/aws_audit/<aws_Account>/<timestamp>/final_report_ and give us a screenshot for the  directory listing of _final_report._

**Comment by Leectan** [comment]
<img width="1012" alt="1" src="https://user-images.githubusercontent.com/24819052/37778408-44849132-2dc0-11e8-98dd-a2e5d56ba29c.png">
<img width="809" alt="screen shot 2018-03-22 at 10 26 51 am" src="https://user-images.githubusercontent.com/24819052/37778420-4b37c120-2dc0-11e8-83b1-e3789f81ee6f.png">
<img width="668" alt="2" src="https://user-images.githubusercontent.com/24819052/37778421-4b4d98ce-2dc0-11e8-8d79-ee6bb8e4bf4f.png">

**Comment by shivankar-madaan** [comment]
So is the issue currently only with Scout2 ?

**Comment by Leectan** [comment]
above are the files and directory for the cs-suite. I have tested on 2 aws accounts, one was able to generate the scout2 report, but not the other. Ip-audit could not be generated for neither accounts.

**Comment by shivankar-madaan** [comment]
IP audit ,basically needs to run separately from AWS audit
For Linux box u run it as 
`python cs.py -aip "host_ip" -pem "pem_file_location"` (this try logging in as  default ec2-user)

**Comment by Leectan** [comment]
@shivankar-madaan both scout2 and Ip audit. @jayeshchauhan, exactly, ip-audit was never generated, any suggestion to fix this type of issue?

**Comment by Leectan** [comment]
@shivankar-madaan, so I should run the IP audit on ec2 server rather than my local machine? does it map the entire aws account or just specific VPC or ec2 instance?

**Comment by shivankar-madaan** [comment]
You can run the IP audit  on your local machine as well or your ec2-server
Just make sure that you have provided the right aws-region(when `aws configure` was run)

**Comment by shivankar-madaan** [comment]
it should work with Unix as well
So we have parameters option as `-aip` (audit_ip) which is manadatory
`-u` user-name,if you want to use any other user than ec2-user(which is default)
`-pem` pem file location
`-p` password,this is basically if you use password along with the pem file,or if you use just the password and not the pem file

**Comment by Leectan** [comment]
<img width="1082" alt="1" src="https://user-images.githubusercontent.com/24819052/37837249-224d98ea-2e8b-11e8-82e5-0ce1ac28670e.png">

**Comment by Leectan** [comment]
<img width="781" alt="2" src="https://user-images.githubusercontent.com/24819052/37837427-828e2de6-2e8b-11e8-825e-40eac32f3081.png">

**Comment by shivankar-madaan** [comment]
Could you please try doing a scp manually as well
I mean the command under the line  `LINUX BOX FOUND!!!`
lets see what error we get and we can then go ahead based on that

**Comment by shivankar-madaan** [comment]
Hey please let us know if you need any help on this, or if we could close this

**Comment by shivankar-madaan** [comment]
please re-open , if there's any issue on the same still exists.

**Comment by devendrab** [comment]
I am facing the same issue while running cs audit for AWS. It don't generate the Scout2 report and its directory as "report/AWS/aws_audit/<account>/<timestamp>/scout2_report"  I get following error while accessing Scout2 reports.
---------------------
Error response
Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.
---------------------

I tried to run cs-suit in AWS ec2 instance with Ubuntu[16.04, 18.04], CentOS 7 and Amzon AMI. All three instance had same results. No Scout2 reports are generated using cs.py. 

However when I individually run Scout2 from cs-suite/tools/Scout2/Scout2.py" it generates the report in "cs-suite/tools/Scout2/scout2-report/report.html"
